### PR TITLE
Governance model proposal

### PR DESCRIPTION
**Pull request by jponge**
* Governance document from the initial public Google Docs draft
* Initial list of maintainers based on the current projects
* Tweaks to README.adoc

### CODE REVIEW

**Comment by jponge** [comment]
Ping @vietj @FroMage @cescoffier @pmlopes

**Comment by jponge** [comment]
Note: I cannot merge since I'm not part of this org 😉

**Comment by vietj** [comment]
I think we are still lacking a part about the asset administration, like this organisation.

Currently most members are owners / admin and can grant any app whatever they want to.

It would be good to clarify who is empowered to administer asset and how the organisation administration happens, e.g if a repo wants to integrate with such CI, how can it be granted or not, etc...

**Comment by jponge** [comment]
I propose to:

1. keep giving all maintainers (the ones who have vote power) admin permissions over the whole organization, and
2. request that permission to grant access to some 3rd-party service is subject to a vote.

**Comment by vietj** [comment]
keep in mind that admin access means potentially the right to transfer / delete organisation, we're not only talking about thirdparty integration here.

**Comment by jponge** [comment]
@vietj Here are some changes wrt administration

**Comment by jponge** [comment]
@vietj @FroMage @cescoffier @pmlopes This PR has been in the air for some time. I'd like to see progress here to push reactiverse forward 😉 

Do you see other concerns on governance, or can we just go ahead with this one as a start?

**Comment by FroMage** [comment]
LGTM. :shipit:

**Comment by vietj** [comment]
LGTM

**Pull request merged**
