### PR TITLE
Project termination process

### PR DESCRIPTION
**Pull request by jponge**
This is a proposal to terminate projects.

@reactiverse/maintainers please vote

### CODE REVIEW

**Comment by pmlopes** [comment]
:+1:

**Comment by vietj** [comment]
I think that we should give the opportunity during the termination process for somebody to speak up and continue the project, i.e if the project is terminating because there is no maintainer I believe it is important to allow somebody to speak up.

**Comment by jponge** [comment]
@vietj added a section to grant 2 weeks to find new maintainers _in parallel_ of the termination vote.

**Comment by tsegismont** [comment]
+1

**Comment by FroMage** [comment]
+1

**Comment by vietj** [comment]
+1

**Comment by jponge** [comment]
@aesteve @romalev Not sure you saw this 😉

**Comment by romalev** [comment]
+1

**Comment by pmlopes** [comment]
Hi, this just came to mi mind: http://tuxdiary.com/2015/06/14/ublock-origin/

Personally I don't know how one can prevent abusive behavior, but in the "find new maintainer" there should be restrictions such as changing licences/remove copyrights without a full vote too. This would ensure that the new maintainer would not misrepresent the previous author(s).

**Comment by vietj** [comment]
@pmlopes agreed, but it should be another issue as it's not related to this issue ?

**Comment by jponge** [comment]
That'd be new maintainer under the Reactiverse umbrella, hence governance.

**Comment by aesteve** [comment]
A little late to the party, but 👍

**Comment by jponge** [comment]
:-)

**Pull request merged**
